FROM node:20-alpine

RUN apk add --no-cache netcat-openbsd

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY Docker/.env .env

COPY . .

RUN chmod +x ./scripts/start-dev.sh

EXPOSE 3000

CMD ["./scripts/start-dev.sh"]
