FROM node:20-alpine

RUN apk add --no-cache netcat-openbsd curl

WORKDIR /app

COPY package*.json ./

RUN npm ci && npm cache clean --force

COPY . .
COPY Docker/.env .env

RUN npx prisma generate

RUN npm run build

RUN chmod +x ./scripts/start-prod.sh

EXPOSE 3000

CMD ["./scripts/start-prod.sh"]
