FROM node:20-alpine

RUN apk add --no-cache netcat-openbsd dos2unix

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY Docker/.env .env

COPY . .

RUN dos2unix ./scripts/start-dev.sh && chmod +x ./scripts/start-dev.sh

EXPOSE 3000

CMD ["sh", "./scripts/start-dev.sh"]
